Fix CI error
Although not reproduceable locally, CI failed with
```
ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False
```

Now assigning a `numpy.ones()` instead of resizing.