Capture error due to invalid coordinate metadata
When validating amns_data in DD 3.38.1. the following error was raised:
`AttributeError: 'IDSStructure' object has no attribute 'shape'`